// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGF-AUutxZSVYoLUrXwJEsMovyXkNYruw',
    appId: '1:397440359795:web:316eabdc1a5d08188bf906',
    messagingSenderId: '397440359795',
    projectId: 'push-notifications-abd1a',
    authDomain: 'push-notifications-abd1a.firebaseapp.com',
    storageBucket: 'push-notifications-abd1a.appspot.com',
    measurementId: 'G-4G9H3EVEW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaX-BNwpnlAvfNtF1aQgYHHSXMCbd_DfQ',
    appId: '1:397440359795:android:5440ccd17dc252be8bf906',
    messagingSenderId: '397440359795',
    projectId: 'push-notifications-abd1a',
    storageBucket: 'push-notifications-abd1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA-URse-WTFvwXruRvDW9PsDntcJWD-pk',
    appId: '1:397440359795:ios:a2102fe9ad51e0938bf906',
    messagingSenderId: '397440359795',
    projectId: 'push-notifications-abd1a',
    storageBucket: 'push-notifications-abd1a.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA-URse-WTFvwXruRvDW9PsDntcJWD-pk',
    appId: '1:397440359795:ios:a2102fe9ad51e0938bf906',
    messagingSenderId: '397440359795',
    projectId: 'push-notifications-abd1a',
    storageBucket: 'push-notifications-abd1a.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGF-AUutxZSVYoLUrXwJEsMovyXkNYruw',
    appId: '1:397440359795:web:0471909a5d443b758bf906',
    messagingSenderId: '397440359795',
    projectId: 'push-notifications-abd1a',
    authDomain: 'push-notifications-abd1a.firebaseapp.com',
    storageBucket: 'push-notifications-abd1a.appspot.com',
    measurementId: 'G-GJGEE7WDNG',
  );
}
